#!/bin/bash

NAME=$1
OS_RELEASE=$(lsb_release -rs | cut -f1 -d.)

if [ -z "$1" ]; then
	echo "USAGE: $(basename $0) [PACKAGE_NAME]";
	exit 1;
fi

if [ -e SPECS/${NAME}-${OS_RELEASE}.spec ]; then 
	echo "SPECS/${NAME}-${OS_RELEASE}.spec"; 
	exit 0;
elseif  [ -e SPECS/${NAME}.spec ];
	echo SPECS/${NAME}.spec; 
	exit 0;
else 
	exit 1;
fi